from typing import Protocol, runtime_checkable


@runtime_checkable
class CncClientProtocol(Protocol):
    @property
    def is_connected(self) -> bool: ...

    def connect(self) -> int: ...

    def disconnect(self) -> None: ...

    def is_server_connected(self) -> bool: ...

    def is_server_process_alive(self) -> bool: ...

    def get_state(self) -> int: ...

    def get_job_status(self) -> dict: ...

    def get_positions(self) -> dict: ...

    def get_all_axes_homed(self) -> bool: ...

    def is_motion_enabled(self) -> bool: ...

    def home_all_axes_g28(self) -> int: ...

    def load_job(self, file_name: str) -> int: ...

    def set_job_quantity(self, quantity: int) -> int: ...

    def render_job(self) -> int: ...

    def run_job(self) -> int: ...

    def pause_job(self) -> int: ...

    def start_jog(
        self,
        axis: str,
        direction: int,
        step: float,
        velocity_factor: float,
        continuous: bool,
    ) -> int: ...

    def stop_jog(self, axis: str | None = None) -> int: ...

    def move_to(self, axis: str, position: float, velocity_factor: float) -> int: ...

    def zero_work_axis(self, axis: str) -> int: ...

    def set_work_coordinate(self, axis: str, value: float) -> int: ...

