from typing import Protocol, runtime_checkable


@runtime_checkable
class CncClientProtocol(Protocol):
    @property
    def is_connected(self) -> bool: ...

    def connect(self) -> int: ...

    def disconnect(self) -> None: ...

    def is_server_connected(self) -> bool: ...

    def is_server_process_alive(self) -> bool: ...

    def get_state(self) -> int: ...

    def get_job_status(self) -> dict: ...

    def load_job(self, file_name: str) -> int: ...

    def set_job_quantity(self, quantity: int) -> int: ...

    def render_job(self) -> int: ...

    def run_job(self) -> int: ...

